
; https://docs.platformio.org/page/projectconf.html
[env:megaatmega2560]
platform = atmelavr
board = megaatmega2560
framework = arduino
monitor_speed = 115200
build_flags =
	-std=c++17
lib_deps =
	electroniccats/MPU6050
	alivka/vex5
